gmail:
  credentials_path: config/credentials.json
  token_path: config/token.pickle

email_filter:
  use_label: true              # Set to false if you don't want label filtering
  label_name: Banking
  use_domain_filter: false
  sender_csv: config/bank_senders.csv

openai:
  keyring_service: email_agent
  keyring_user: openai_api_key
  api_base: ""                # override if using a local OpenAI-compatible server

paths:
  accounts_csv: config/accounts.csv
  transactions_csv: data/transactions.csv
  bank_senders_csv: data/bank_senders.csv
  metadata_csv: data/metadata.csv
  runs_csv: data/runs.csv
  flagged_csv: data/flagged_messages.csv
  invoices_dir: Invoices

scraper:
  initial_start_date: "2023-01-01"
  overlap_hours: 1
  max_results: 500
  query: "subject:transaction"

parser:
  provider: "hf"                     # one of: openai | llamacpp | hf

  # ── OpenAI settings ───────────────────────────────────────
  openai_model: "gpt-4"

  # ── llama-cpp settings ────────────────────────────────────
  model_path: "models/llama-3.1-8B-Instruct-f32.bin"
  n_ctx: 2048
  seed: 42

  # ── HuggingFace-Quantized settings ───────────────────────
  hf_model_id: "meta-llama/Llama-3.2-3B-Instruct"
  max_new_tokens: 512
  quant_bits: 4                      # 0, 4 or 8
  bnb_4bit_quant_type: "nf4"
  bnb_double_quant: true
  bnb_4bit_compute_dtype: "float16"

  #GPU
  device_map: "auto"    # or "none"
  device: 0            # -1 for CPU, or 0 for GPU0

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  dbname: "email_agent_db"
  user: "emailagent"
  schema: "public"
  table: "transactions"
  backup_interval_days: 14