# ── Which connector to use ─────────────────────────────────────────────────
connector: gmail        # currently only 'gmail', but you can add others

connectors:
  gmail:
    credentials_path: config/credentials.json
    token_path:       config/token.pickle

accounts:
  - internal_account_number: "11663427844"
    internal_entity:         "Senzo Msutwana"
    institution:             "Discovery"
    currency:                "ZAR"
  - internal_account_number: "16292977375"
    internal_entity:         "Senzo Msutwana"
    institution:             "Discovery"
    currency:                "ZAR"
  - internal_account_number: "4057425883"
    internal_entity:         "Civil Projects Engineers"
    institution:             "ABSA"
    currency:                "ZAR"
  - internal_account_number: "9322072897"
    internal_entity:         "Civil Projects Engineers"
    institution:             "ABSA"
    currency:                "ZAR"


email_filter:
  use_label: true              # Set to false if you don't want label filtering
  label_name: Banking
  use_domain_filter: false
  sender_csv: config/bank_senders.csv

openai:
  keyring_service: email_agent
  keyring_user: openai_api_key
  api_base: ""                # override if using a local OpenAI-compatible server

paths:
  accounts_csv: config/accounts.csv
  transactions_csv: data/transactions.csv
  run_folder: data/runs
  metadata_csv: data/metadata.csv
  runs_csv: data/runs.csv
  flagged_csv: data/flagged_messages.csv
  invoices_dir: Invoices



# This is a list of synonyms for the fields in the transactions table. This helps with parsing when people use different terms for the same thing.
synonyms:
  date:
    - trans_date
    - date_of_transaction
    - txn_date
  account_name:
    - acct_name
    - account
    - account_title
  account_number:
    - acct_number
    - account_no
    - acc_num
  internal_entity:
    - Payment made by
    - Payment made from
    - Paid from
    - “Payment originated from”
  institution:
    - bank
    - bank_name
  external_entity:
    - payee
    - recipient
    - merchant
    - vendor
    - Payment made to
    - Paid to
    - “Beneficiary”
    - “Payment received by”
  description:
    - narrative
    - desc
    - details
  amount:
    - amt
    - value
    - transaction_amount
    - for the amount of
  currency:
    - curr
    - currency_code
  available_balance:
    - balance
    - avail_balance
    - available


scraper:
  initial_start_date: "2023-01-01"
  overlap_hours: 1
  max_results: 100 
  query: "subject:transaction"
  parse_pdfs: false      # if false, any PDF attachments will be skipped
  save_attachments: true           # turn off if you don't need PDFs to be saved
  pdf_password: "201766138207"        # your 13-digit ID number



parser:
  provider: "hf"                     # one of: openai | llamacpp | hf

  # ── OpenAI settings ───────────────────────────────────────
  openai_model: "gpt-4"

  # ── llama-cpp settings ────────────────────────────────────
  model_path: "models/llama-3.1-8B-Instruct-f32.bin"
  n_ctx: 2048
  seed: 42

  # ── HuggingFace-Quantized settings ───────────────────────
  hf_model_id: "meta-llama/Llama-3.2-3B-Instruct"
  max_new_tokens: 512
  quant_bits: 4                      # 0, 4 or 8
  bnb_4bit_quant_type: "nf4"
  bnb_double_quant: true
  bnb_4bit_compute_dtype: "float16"

  #GPU
  device_map: "auto"    # or "none"
  device: 0            # -1 for CPU (incl HPC), or 0 for GPU0

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  dbname: "email_agent_db"
  user: "emailagent"
  schema: "public"
  table: "transactions"

scheduler:
  interval: "daily"                # daily | hourly | cron
  cron_expr: "0 3 * * *"           # used if interval == cron